### PR TITLE
fix(logging): combine newline-split stdout messages into one log entry

### LINKED ISSUE #9557: [User reported] Using `\n` in a log message creates 2 separate messages
This is a user-reported issue from the 2025 DevTools user survey.

A user reports that using `\n` in a log message causes it two appear as 2 separate messages in DevTools.

### PR DESCRIPTION
**Pull request by rishika0212**
Fixes https://github.com/flutter/devtools/issues/9557

When `debugPrint('line1\nline2')` is called, the VM sends the message as two separate stdout events: `'line1\n'` and `'line2'`. The existing 1ms buffer in `StdoutEventHandler` only handled the case where the second event is a lone `'\n'` (e.g. `foo` followed by `\n`). It did not handle embedded newlines, so each chunk became a separate log entry
in the Logging screen.

The fix extends the buffer logic: if the buffered message ends with `'\n'`, the next incoming message is treated as a continuation of the same print statement and combined into a single log entry.

`_StdoutEventHandler` was also exposed as `StdoutEventHandler` with `@visibleForTesting` to allow direct unit testing of the handler logic.

**Before:** `debugPrint('line1\nline2')` appeared as two separate log entries.
**After:** It appears as a single log entry.

### General checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
### Issues checklist
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I listed at least one issue which has the [`contributions-welcome`] or [`good-first-issue`] label.
- [ ] I did not list at least one issue with the [`contributions-welcome`] or [`good-first-issue`] label. I understand this means my PR might take longer to be reviewed.
### Tests checklist
- [x] I added new tests to check the change I am making...
- [ ] OR there is a reason for not adding tests, which I explained in the PR description.
### AI-tooling checklist
- [ ] I did not use any AI tooling in creating this PR.
- [x] OR I did use AI tooling, and...
    * [x] I read the [AI contributions guidelines] and agree to follow them.
    * [x] I reviewed all AI-generated code before opening this PR.
    * [x] I understand and am able to discuss the code in this PR.
    * [x] I have verifed the accuracy of any AI-generated text included in the PR description.
    * [x] I commit to verifying the accuracy of any AI-generated code or text that I upload in response to review comments.
### Feature-change checklist
- [ ] This PR does not change the DevTools UI or behavior and...
    * [ ] I added the `release-notes-not-required` label or left a comment requesting the label be added.
- [x] OR this PR does change the DevTools UI or behavior and...
    * [x] I added an entry to `packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md`.
    * [ ] I included before/after screenshots and/or a GIF demo of the new UI to my PR description.
    * [x] I ran the DevTools app locally to manually verify my changes.

### CODE REVIEW

File: packages/devtools_app/lib/src/screens/logging/logging_controller.dart [hunk 1]
```diff
@@ -876,6 +873,28 @@ class _StdoutEventHandler {
         return;
       }
 
+      // If the buffered message ends with a newline, the next message is a
+      // continuation of the same print statement (e.g. debugPrint('line1\nline2')
+      // is sent by the VM as two events: 'line1\n' and 'line2'). Combine them
+      // into a single log entry.
+      // See: https://github.com/flutter/devtools/issues/9557
+      if (buffer!.details!.endsWith('\n')) {
```
Comment (srawlins) [inline packages/devtools_app/lib/src/screens/logging/logging_controller.dart]: We should do something to avoid the repeated `buffer!` here. Let's make `buffer` private, for one thing. But since it's mutable, that probably won't help promotion.

Up above, can we make a local variable from the non-null `buffer` result? Like

```
if (buffer case final currentBuffer?) {
  // Here, `currentBuffer` is non-null.
  // Read from `currentBuffer` for new `logData`,
  // and write to `buffer` when writing
  // `buffer = null;`.
}
```

We might even want to move lines 858-899 into a helper function, as `handle()` is getting quite long now.

**Review by srawlins — CHANGES_REQUESTED** [review]
Just a preliminary review so we can kick off CI.

File: packages/devtools_app/lib/src/screens/logging/logging_controller.dart (hunk 1 above)
Comment (rishika0212) [reply packages/devtools_app/lib/src/screens/logging/logging_controller.dart]: Implemented, thanks
Addressed this by making the stdout buffer private and using a promoted local (if (_buffer case final currentBuffer?)) to remove repeated non-null assertions.
Also extracted buffered-event handling into a helper to keep handle() shorter; tests still pass, including newline continuation coverage.

File: packages/devtools_app/lib/src/screens/logging/logging_controller.dart [hunk 2]
```diff
@@ -1,3 +1,5 @@
+
+
```
Comment (srawlins) [inline packages/devtools_app/lib/src/screens/logging/logging_controller.dart]: Please remove these lines (`dart format` should not retain empty lines like this...)

**Review by srawlins — CHANGES_REQUESTED** [review]

File: packages/devtools_app/lib/src/screens/logging/logging_controller.dart (hunk 2 above)
Comment (rishika0212) [reply packages/devtools_app/lib/src/screens/logging/logging_controller.dart]: Good catch, I missed that. Fixed now and reran dart format on that file.

**Review by elliette — CHANGES_REQUESTED** [review]
Hi @rishika0212 - do you mind adding before/after screenshots to the PR description for this change? Thank you!

**Comment by rishika0212** [comment]
> Hi @rishika0212 - do you mind adding before/after screenshots to the PR description for this change? Thank you!

Before (master): a single multiline log message using \n appears as two separate log entries (FIRST LINE and SECOND LINE).

Screenshot 2026-04-08 140203

After (this PR): the same multiline message appears as one log entry, with both lines shown together in Details.

Screenshot 2026-04-08 135505

File: packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart [hunk 3]
```diff
@@ -162,11 +174,17 @@ void main() {
     logStatus('looking for the focused line');
 
     // Look for the line 46 gutter item:
-    final gutter46Finder = findGutterItemWithText('46');
+    final gutter46Finder = await retryUntilFound(
```
Comment (elliette) [inline packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart]: Why were these changes added?

File: packages/devtools_app/integration_test/test/live_connection/network_screen_test.dart [hunk 4]
```diff
@@ -100,13 +100,19 @@ final class _NetworkScreenHelper {
   final WidgetTester _tester;
 
   Future<void> clear() async {
+    final controller = screenControllers.lookup<NetworkController>();
```
Comment (elliette) [inline packages/devtools_app/integration_test/test/live_connection/network_screen_test.dart]: Same question as above - why was this test changed?

File: packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart [hunk 5]
```diff
@@ -609,13 +609,23 @@ class EvalOnDartLibrary extends DisposableController
...
   }) {
     return addRequest<T>(isAlive, () async {
-      final T value = await service.getObject(
-        _isolateRef!.id!,
-        instance.id!,
-        offset: offset,
-        count: count,
-      ) as T;
-      return value;
+      try {
```
Comment (elliette) [inline packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart]: It looks like this (and the DWDS specific code) is solving a different issue than https://github.com/flutter/devtools/issues/9557

Could you pull this code into a separate PR and file/link the issue it's fixing? Thanks!

File: packages/devtools_shared/lib/src/test/integration_test_runner.dart [hunk 6]
```diff
@@ -49,7 +49,7 @@ class IntegrationTestRunner with IOMixin {
         '--driver=$testDriver',
         '--target=$testTarget',
         '-d',
-        headless ? 'web-server' : 'chrome',
+        'chrome',
```
Comment (elliette) [inline packages/devtools_shared/lib/src/test/integration_test_runner.dart]: Please don't remove the web-server option

**Review by elliette — CHANGES_REQUESTED** [review]

File: packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart (hunk 3 above)
Comment (rishika0212) [reply packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart]: I added this while trying to stabilize widespread CI failures. Since it is out of scope for this PR, I removed it.

File: packages/devtools_app/integration_test/test/live_connection/network_screen_test.dart (hunk 4 above)
Comment (rishika0212) [reply packages/devtools_app/integration_test/test/live_connection/network_screen_test.dart]: same reason
This change is now removed from this PR.

File: packages/devtools_shared/lib/src/test/integration_test_runner.dart (hunk 6 above)
Comment (rishika0212) [reply packages/devtools_shared/lib/src/test/integration_test_runner.dart]: I switched this during CI triage, but it should not be in this PR. I reverted it and restored web-server support.

File: packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart (hunk 5 above)
Comment (rishika0212) [reply packages/devtools_app_shared/lib/src/service/eval_on_dart_library.dart]: I added this as part of CI stabilization, but you are right it is separate scope

**Review by srawlins — APPROVED** [review]

**Comment by srawlins** [comment]
LGTM, @elliette

**Comment by srawlins** [comment]
Thanks again! I just re-templated the release notes, so you'll have to resolve that conflict.

**Review by elliette — APPROVED** [review]

**Review by srawlins — APPROVED** [review]

File: packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md [hunk 7]
```diff
@@ -43,7 +43,7 @@ TODO: Remove this section if there are not any updates.
 
 ## Logging updates
 
-TODO: Remove this section if there are not any updates.
+- Fixed an issue where log messages containing newline characters were incorrectly split into multiple separate entries in the Logging screen. [#TODO](https://github.com/flutter/devtools/pull/TODO)
```
Comment (kenzieschmoll) [inline packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md]: please replace "TODO" with this PR number

Comment (kenzieschmoll) [inline packages/devtools_app/release_notes/NEXT_RELEASE_NOTES.md]:
```suggestion
- Fixed an issue where log messages containing newline characters were incorrectly split into multiple separate entries in the Logging screen. [#9757](https://github.com/flutter/devtools/pull/9757)
```

**Review by srawlins — APPROVED** [review]
