### PR TITLE
Fixed search, auto-complete, and added tests.

### LINKED ISSUE #2615: Incremental search seems break with table tree
Memory view search works but other times does not correctly scroll into the view the node found.

### PR DESCRIPTION
**Pull request by terrylucas**
- Cleaned up auto-complete to correctly handle Enter key to select current highlighted entry in the drop-down list.
- Handle up/down arrow to change the highlighted entry in the auto-complete drop-down list.
- Added loading and saving of allocation data (ClassHeapDetailStats).
- Added tests monitor allocations, tracking and search and auto-complete.

Fixes #2615.

### CODE REVIEW

File: packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart [hunk 1]
```diff
@@ -643,6 +642,30 @@ class HeapTreeViewState extends State<HeapTree>
     controller.monitorAllocations = currentAllocations;
   }
 
+  void highlightDropdown(bool directionDown) {
+    final maxItems = controller.searchAutoComplete.value.length;
+    var indexToSelect = controller.currentDefaultIndex;
+    if (directionDown) {
+      // Select next item in auto-complete overlay.
+      if (++indexToSelect >= maxItems) {
```
Comment (jacob314) [inline packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart:650]: nit: having side effects in an iff statement is a bit surprising. Maybe change to 
```dart
++indexToSelect;
if (indexToSelect >= maxItems)
```
so the code is more obvious to people reading it who might not notice the side effects.

File: packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart [hunk 2]
```diff
@@ -643,6 +642,30 @@ class HeapTreeViewState extends State<HeapTree>
...
+        // Greater than max go back to top list item.
+        indexToSelect = 0;
+      }
+    } else {
+      // Select previous item item in auto-complete overlay.
+      if (--indexToSelect < 0) {
```
Comment (jacob314) [inline packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart:656]: same comment as above.

File: packages/devtools_testing/pubspec.yaml [hunk 3]
```diff
@@ -2,16 +2,16 @@ name: devtools_testing
 description: Package of shared testing code for Dart DevTools.
 # Note: this version should only be updated by running tools/update_version.sh
 # that updates all versions of packages from packages/devtools.
-version: 0.9.8-dev.1
+version: 0.9.8-dev.2
```
Comment (jacob314) [inline packages/devtools_testing/pubspec.yaml:5]: nit: any reason why the version is updated as part of this CL?

File: packages/devtools_shared/lib/src/memory/memory_json.dart [hunk 4]
```diff
@@ -45,38 +60,41 @@ class MemoryJson {
...
+  /// JSON payload field "dart<T>DevToolsScreen" has a value of "memory" e.g.,
   ///   "dartDevToolsScreen": "memory"
   bool get isMemoryPayload => _memoryPayload;
 
   /// If data is empty check isMatchedVersion and isMemoryPayload to ensure the
   /// JSON file loaded is a memory file.
-  final List<HeapSample> data = [];
-
-  // TODO(terry): Expose encode/decode to Timeline too.
+  final List<T> data = [];
```
Comment (jacob314) [inline packages/devtools_shared/lib/src/memory/memory_json.dart:69]: not a new issue but I think we are overall trying to use the style of
final data = <T>[];

**Review by jacob314 — APPROVED** [review]
lgtm

File: packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart (hunk 1 above)
Comment (terrylucas) [reply packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart:650]: Yep, fixed.

File: packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart (hunk 2 above)
Comment (terrylucas) [reply packages/devtools_app/lib/src/memory/memory_heap_tree_view.dart:656]: Done.

File: packages/devtools_testing/pubspec.yaml (hunk 3 above)
Comment (terrylucas) [reply packages/devtools_testing/pubspec.yaml:5]: No, since I had to update a few packages I ran the update script which updated all packages.

File: packages/devtools_shared/lib/src/memory/memory_json.dart (hunk 4 above)
Comment (terrylucas) [reply packages/devtools_shared/lib/src/memory/memory_json.dart:69]: Done.

File: packages/devtools_app/lib/src/ui/search.dart [hunk 5]
```diff
@@ -124,10 +126,19 @@ mixin AutoCompleteSearchControllerMixin on SearchControllerMixin {
     final RenderBox box = searchFieldKey.currentContext.findRenderObject();
 
     final autoCompleteTiles = <ListTile>[];
-    for (final matchedName in searchAutoComplete.value) {
+    final count = searchAutoComplete.value.length;
+    for (var index = 0; index < count; index++) {
+      final matchedName = searchAutoComplete.value[index];
+      Color activeColor;
+      if (currentDefaultIndex == index) {
+        activeColor = Colors.grey[700];
```
[the remark this answers is not in the document]
Comment (terrylucas) [reply packages/devtools_app/lib/src/ui/search.dart:134]: No, changed to a better dark and light mode colors. e.g.,

```
  // Highlight color for an selected item in the autocomplete dropdown list.
  Color get autoCompleteHighlightColor =>
      isLight ? Colors.grey[300] : Colors.grey[700];

 tileColor: currentDefaultIndex == index
      ? colorScheme.autoCompleteHighlightColor
      : colorScheme.defaultBackgroundColor,
```

image

image
