### PR TITLE
fix splitter layout issues

### LINKED ISSUE #880: Splitters not starting at specified start ratio
Splitters are not starting at the correct ratio. These examples repro every time on initial page load.
Screen Shot 2019-08-06 at 7 58 51 AM
Screen Shot 2019-08-06 at 7 59 09 AM

@jacob314 I confirmed this started happening after https://github.com/flutter/devtools/pull/873 landed.

### PR DESCRIPTION
**Pull request by devoncarew**
- fix splitter layout issues
- fix #880; fix https://github.com/flutter/devtools/issues/905

Downgrading from package:split 0.0.4 to 0.0.2 addressed the issue.

### CODE REVIEW

File: packages/devtools/lib/src/logging/logging.dart [hunk 1]
```diff
@@ -103,11 +103,13 @@ class LoggingScreen extends Screen {
       // configure the table / details splitter. Setting up this splitter works
       // better once the UI is active in the DOM so we have to delay it until
       // we get the entering event.
-      split.fixedSplitBidirectional(
+      // TODO(devoncarew): Use fixedSplitBidirectional when we move to
+      // package:split v0.0.4.
+      split.flexSplit(
```
Comment (jacob314) [inline packages/devtools/lib/src/logging/logging.dart]: flex split definitely won't work for the structured logging cases due to flex edge cases. Can you file a bug to track it.

Comment (devoncarew) [reply packages/devtools/lib/src/logging/logging.dart]: Ah, sure, will do.

Comment (devoncarew) [reply packages/devtools/lib/src/logging/logging.dart]: https://github.com/flutter/devtools/issues/914
