### PR TITLE
Move the performance controller to the top level controllers and make…

### LINKED ISSUE #1230: Set state called after dispose in performance tab
To fix we likely need to disconnect the view from the controller on dispose. The existing performance view was missing this state management logic as it was hard to actually disconnect the views in the dart:html app.
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() called after dispose(): PerformanceBodyState#984ff(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1105:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1140:6)
#2      PerformanceBodyState.initState.<anonymous closure> (package:devtools_app/src/performance/flutter/performance_screen.dart:51:7)
<asynchronous suspension>
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._complete (dart:async/future_impl.dart:512:7)
#9      new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
#10     _rootRun (dart:async/zone.dart:1120:38)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

### PR DESCRIPTION
**Pull request by DaveShuckerow**
… it disposable.

Fixes #1230.

### CODE REVIEW

File: packages/devtools_app/lib/src/performance/flutter/performance_screen.dart [hunk 1]
```diff
@@ -116,7 +116,8 @@ class PerformanceScreenBody extends StatelessWidget {
     );
   }
 
-  Widget _buildCpuProfiler(CpuProfileData data) {
+  Widget _buildCpuProfiler(
+      PerformanceController controller, CpuProfileData data) {
```
Comment (kenzieschmoll) [inline packages/devtools_app/lib/src/performance/flutter/performance_screen.dart]: trailing comma

Comment (DaveShuckerow) [reply packages/devtools_app/lib/src/performance/flutter/performance_screen.dart]: Done.
