### PR TITLE
Handle frames with delay. Fix frame tracking bugs.

### LINKED ISSUE #301: frame tracking code can get out of sync (and possibly not terminate)
I've noticed that the code to determine where frames are in the timeline data can get out of sync occasionally; I normally see a symptom of this where we stop producing frames in the timeline UI.

When this happens, we may also not terminate some calculations - I've noticed runaway CPU usage as well. I'm attaching some console output, and a screenshot of the cpu profiler, for one case I noticed.

```
Error - already set startTime 349489449902 for frame e69.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349489449904, ph: s, id: e69, args: {}}
dart_sdk.js:18331 Error - already set startTime 349489466505 for frame e6a.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349489466507, ph: s, id: e6a, args: {}}
dart_sdk.js:18331 Error - already set startTime 349487833446 for frame e10.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349487833449, ph: s, id: e10, args: {}}
dart_sdk.js:18331 Error - already set startTime 349487850857 for frame e11.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 47619, pid: 98195, ts: 349487850859, ph: s, id: e11, args: {}}
dart_sdk.js:18331 Error - already set endTime 349493988997 for frame f70.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 81155, pid: 98195, ts: 349493988997, ph: f, bp: e, id: f70, args: {}}
dart_sdk.js:18331 Error - already set endTime 349493998178 for frame f71.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 81155, pid: 98195, ts: 349493998178, ph: f, bp: e, id: f71, args: {}}
dart_sdk.js:18331 Error - already set endTime 349497921785 for frame 1046.
TraceEvent - {name: PipelineItem, cat: Embedder, tid: 81155, pid: 98195, ts: 349497921785, ph: f, bp: e, id: 1046, args: {}}
```

screen shot 2019-02-16 at 1 27 56 pm

cc @kenzieschmoll

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Use a min heap to keep trace events in timestamp order. Handle events after they have been on the heap for one second. Restore tree imbalance caused by duplicate trace events from the engine.

Fixes #301.

While trying to fix this, I came across several edge cases we have not yet considered. The engine will send duplicate trace events on occasion. These duplicates lead to nesting issues with the TimelineEvent structure and result in an unbalanced tree. We can recover a balanced state in most of these edge cases, but some cannot be covered because doing so would violate other guarantees we need in order to build the tree. If we cannot restore balance in the event tree, we drop the node and don't add it to any pending frames. This happens very rarely, so doing so will not result in a broken experience for the user.

### CODE REVIEW

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 1]
```diff
@@ -48,14 +53,73 @@ class TimelineData {
   /// The current node in the tree structure of GPU duration events.
   TimelineEvent _gpuEventNode;
 
+  final HeapPriorityQueue<TraceEventWrapper> _cpuTraceHeap =
+      HeapPriorityQueue(traceComparator);
+
+  final HeapPriorityQueue<TraceEventWrapper> _gpuTraceHeap =
+      HeapPriorityQueue(traceComparator);
+
+  static int traceComparator(TraceEventWrapper a, TraceEventWrapper b) {
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: nit: move this to the TraceEventWrapper itself. Seems reasonable in general.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 2]
```diff
@@ -48,14 +53,73 @@ class TimelineData {
...
+    final compare = a.event.timestampMicros.compareTo(b.event.timestampMicros);
+    if (compare == 0 && a.event.name == b.event.name) {
+      // If the events share both their name and their timestamp, ensure the
+      // DurationBegin event has priority over DurationEnd events. Duration
+      // events are the only case where this should matter - we must have a
+      // begin event followed by an end event and we rely on this ordering.
+      return a.event.phase.compareTo(b.event.phase);
+    } else if (compare == 0) {
+      // Otherwise if the events share a timestamp, order them in the order we
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: Technically a Comparable function should return 0 if the objects are equal.
What case will that break? 
Potentially returning 0 could cause bugs depending on where the comparable is used.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 3]
```diff
@@ -326,6 +370,29 @@ class TimelineData {
...
+      return TimelineEventType.cpu;
+    } else if (event.threadId == gpuThreadId) {
+      return TimelineEventType.gpu;
+    } else {
+      return TimelineEventType.unknown;
+    }
+  }
+
+  bool _shouldProcessTraceEvent(TraceEvent event) {
+    const List<String> phaseWhitelist = ['s', 'f', 'B', 'E', 'X'];
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: this would be faster as a Set literal  \o/

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 4]
```diff
@@ -326,6 +370,29 @@ class TimelineData {
...
+    return phaseWhitelist.contains(event.phase) &&
+        // Do not process Garbage Collection events.
+        event.category != 'GC' &&
+        // Do not process MessageLoop::RunExpiredTasks events. These events can
+        // either a) start outside of our frame start time, b) parent irrelevant
+        // events, or c) parent multiple event flows - none of which we want.
+        event.name != 'MessageLoop::RunExpiredTasks' &&
+        // Only process events from the CPU or GPU thread.
+        (event.isGpuEvent || event.isCpuEvent);
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: what events aren't gpu or cpu?

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 5]
```diff
@@ -688,3 +755,9 @@ class TraceEvent {
   String toString() => '$type event [id: $id] [cat: $category] [ph: $phase] '
       '$name - [timestamp: $timestampMicros] [duration: $duration]';
 }
+
+class TraceEventWrapper {
+  TraceEventWrapper(this.event, this.timeReceived);
+  TraceEvent event;
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: nit: make both fields final.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart (hunk 1 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/timeline/timeline_protocol.dart]: donel

File: packages/devtools/lib/src/timeline/timeline_protocol.dart (hunk 2 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/timeline/timeline_protocol.dart]: Modified comparator - it should never return 0, but instead default to comparing the events in the order we received them.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart (hunk 4 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/timeline/timeline_protocol.dart]: If we received events from another thread, these would be neither cpu or gpu events. We want to make sure we don't process these.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart (hunk 3 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/timeline/timeline_protocol.dart]: done.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart (hunk 5 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/timeline/timeline_protocol.dart]: done. Also added id.

File: packages/devtools/lib/src/timeline/frame_flame_chart.dart [hunk 6]
```diff
@@ -125,12 +122,16 @@ class FrameFlameChart extends CoreElement {
     _frame = frame;
     _resetChart();
 
-    if (_debugEventTrace && frame != null) {
-      final StringBuffer buf = new StringBuffer();
+    if (debugTimeline && frame != null) {
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/frame_flame_chart.dart]: Nit: you could implement Diagnosticable for this sort of large debugging string output.

File: packages/devtools/lib/src/timeline/timeline.dart [hunk 7]
```diff
@@ -224,4 +228,85 @@ class TimelineScreen extends Screen {
...
+              html.Url.createObjectUrl(
+                  html.Blob([debugTraceEvents.toString()])));
+          debugTraceEventsOutput.setAttribute('download', 'trace_output.txt');
+          debugTraceEventsOutput.style.display = 'none';
+          html.document.body.append(debugTraceEventsOutput);
+          debugTraceEventsOutput.click();
+          debugTraceEventsOutput.remove();
+
+          // Significant events in the frame tracking process.
+          final debugFrameTrackingOutput = html.document.createElement('a');
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline.dart]: make this a util helper function. I'm sure this is not the last time we will want to download large files from the tool.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 8]
```diff
@@ -5,20 +5,44 @@
...
 // https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview
 
-// Switch this flag to true to dump timeline events to console.
-bool _debugEventTrace = false;
+// Switch this flag to true collect debug info from the timeline protocol. This
+// will also add a button to the timeline page that will download files with
+// this info on click.
+bool debugTimeline = false;
+
+/// Strings that we will build and output to text files for debug purposes.
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: nit Strings --> Buffers

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 9]
```diff
@@ -5,20 +5,44 @@
...
+///
+/// [debugTraceEvents]: trace events in the order we receive them
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: Match the dart doc comment format. You should have a comment above each field instead of one comment for multiple fields.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 10]
```diff
@@ -5,20 +5,44 @@
...
 enum TimelineEventType {
   cpu,
   gpu,
   unknown,
 }
 
+/// Epsilon in micros used for determining it an event fits within a given frame
+/// boundary.
+///
+/// This epsilon will not be used if the duration of the event exceeds 2000
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: you mean if the duration of the event is less than  not that it exceeds, right?

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 11]
```diff
@@ -5,20 +5,44 @@
...
+/// micros (2 ms). We do this to hold a requirement that at least half of the
+/// event must fit within the frame boundaries.
+const traceEventEpsilon = 1000;
+
+/// Delay in ms for processing trace events.
+const traceEventDelay = 1000;
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: use Duration objects here so you don't have to comment what the unit is.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 12]
```diff
@@ -36,64 +60,133 @@ class TimelineData {
...
 
   /// Events we have collected and are waiting to add to their respective
   /// frames.
-  final List<TimelineEvent> _pendingEvents = [];
+  final List<TimelineEvent> pendingEvents = [];
 
-  /// The current node in the tree structure of CPU duration events.
-  TimelineEvent _cpuEventNode;
+  /// The current nodes in the tree structures of CPU and GPU duration events.
+  final List<TimelineEvent> currentEventNodes = List.generate(2, (_) => null);
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: [null, null] 
is simpler.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 13]
```diff
@@ -36,64 +60,133 @@ class TimelineData {
...
 
-  /// The current node in the tree structure of GPU duration events.
-  TimelineEvent _gpuEventNode;
+  /// The previously handled DurationEnd event for both CPU and GPU.
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: event --> events?

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 14]
```diff
@@ -36,64 +60,133 @@ class TimelineData {
...
+  ///
+  /// We need this information to balance the tree structures of our event nodes
+  /// if they fall out of balance due to duplicate trace events.
+  List<TraceEvent> previousDurationEndEvents = List.generate(2, (_) => null);
+
+  /// Heaps that order and store trace events as we receive them.
+  final List<HeapPriorityQueue<TraceEventWrapper>> heaps = List.generate(
+    2,
+    (_) => HeapPriorityQueue(TraceEventWrapper.traceComparator),
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: instead of using a custom comparator, have TraceEventWrapper implement Comparable.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 15]
```diff
@@ -36,64 +60,133 @@ class TimelineData {
...
-    if (_debugEventTrace) print(event.toString());
+    if (debugTimeline) {
+      debugTraceEvents.writeln(event.json.toString());
+    }
 
+    // Process flow events now. Process Duration events after a delay.
     switch (event.phase) {
       case 's':
-        _handleFrameStartEvent(event);
+        if (event.name.contains('PipelineItem')) {
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: what should we be doing if this is not a PipelineItem?
document this special case here and elsewhere. Hopefully this special case can be removed as it does not seem robust.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 16]
```diff
@@ -36,64 +60,133 @@ class TimelineData {
...
+  }
+
+  void _processDurationEventsWithDelay(
+      HeapPriorityQueue<TraceEventWrapper> heap) {
+    // Tracks whether we are already processing events on the heap.
+    bool processing = false;
+
+    // Using a periodic timer ensures we will never leave events on the heap
+    // that are ready to process. This should be inexpensive to repeat.
+    Timer.periodic(const Duration(milliseconds: 100), (_) {
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: We should avoid code that keeps a periodic timer going indefinitely. Instead queue a timer if one isn't started. I thought this code looked like that previously.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 17]
```diff
@@ -112,102 +210,149 @@ class TimelineData {
...
-        _maybeAddEvent(current);
+    TimelineEvent current = currentEventNodes[event.type.index];
+
+    if (current == null) return;
+
+    // If the names of [event] and [current] do not match, our event nesting is
+    // off balance due to duplicate events from the engine. Balance the tree so
+    // we can continue processing trace events for [current].
+    if (event.name != current.name) {
+      if (event.json.toString() ==
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: is this really an error if the duration of the two events is zero? We should dig into what this case means on the VM side.
in any case, we should compare based on equality not based on calling toString.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 18]
```diff
@@ -112,102 +210,149 @@ class TimelineData {
...
+        // FrameWork Workload - DurationEnd [previousDurationEndEvent]
+        // FrameWork Workload - DurationEnd ([event] - duplicate)
+        // VSYNC - DurationEnd
+        //
+        return;
+      } else if (current.name ==
+              previousDurationEndEvents[event.type.index]?.name &&
+          current.parent?.name == event.name &&
+          current.children.length == 1 &&
+          current.eventTraces.first.toString() ==
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: same comment as in the previous case

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 19]
```diff
@@ -112,102 +210,149 @@ class TimelineData {
...
+        // FrameWork Workload - DurationEnd [previousDurationEndEvent]
+        // VSYNC - DurationEnd [event]
+        //
+        current.parent.removeChild(current);
+        current = current.parent;
+        currentEventNodes[event.type.index] = current;
+      } else {
+        // The current event node has fallen into an unrecoverable state. Reset
+        // the tracking node.
+        currentEventNodes[event.type.index] = null;
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: when does this case occur? this sort of logic suggests we are not doing things in a robust enough way and we are in danger of displaying the wrong data to users.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 20]
```diff
@@ -112,102 +210,149 @@ class TimelineData {
...
+    // Since this event is complete, move back up the tree to the nearest
+    // incomplete event.
+    while (current.parent?.endTime != null) {
+      current = current.parent;
+    }
+    currentEventNodes[event.type.index] = current.parent;
+
+    // If we have reached a null parent, this event is fully formed.
+    if (current.parent == null) {
+      if (debugTimeline) {
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: this never occurs, right?

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 21]
```diff
@@ -244,36 +389,49 @@ class TimelineData {
...
-  ///
-  /// Returns a bool indicating whether the event was added to the frame.
+  /// Attempts to add [event] to [frame], and returns a bool indicating whether
+  /// the attempt was successful.
   bool _maybeAddEventToFrame(TimelineEvent event, TimelineFrame frame) {
-    assert(frame.isWellFormed);
-
-    // Ensure the event fits within the frame's time boundaries.
-    if (!_eventOccursWithinFrameBoundaries(event, frame)) {
+    // Ensure the frame does not already have an event of this type and that
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: why can't a frame have multiple events of the same type?

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 22]
```diff
@@ -485,46 +666,107 @@ class TimelineEvent {
...
+        }
       }
       return false;
     }
 
-    return findChild(this, childName);
+    return _containsChildWithCondition(this, condition);
+  }
+
+  void maybeRemoveDuplicate() {
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: why are we removing duplicates here as well?

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 23]
```diff
@@ -573,6 +812,22 @@ class TimelineEvent {
     }
   }
 
+  void formatFromRoot(StringBuffer buf, String indent) {
+    getRoot().format(buf, indent);
+  }
+
+  void writeTraceToBuffer(StringBuffer buf) {
+    if (eventTraces.isNotEmpty) {
+      buf.writeln(eventTraces.first.toString());
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: why is first special cased? this output format seems hard for someone who is not familiar with it to understand.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 24]
```diff
@@ -688,3 +943,21 @@ class TraceEvent {
   String toString() => '$type event [id: $id] [cat: $category] [ph: $phase] '
       '$name - [timestamp: $timestampMicros] [duration: $duration]';
 }
+
+int _orderId = 0;
+
+class TraceEventWrapper {
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: implement Comparable instead of adding a static method

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 25]
```diff
@@ -688,3 +943,21 @@ class TraceEvent {
...
+  TraceEventWrapper(this.event, this.timeReceived) : orderId = _orderId++;
+  final TraceEvent event;
+  final num timeReceived;
+  final int orderId;
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: orderId --> id

**Comment by jacob314** [comment]
What we need to figure out are some invariants to apply so we can display all the data without needing to toss some data out or otherwise fixup the tree. Sometimes the best way to solve a problem like this is to take a step back and figure out how to simplify when the logic gets too complex. For example, I'm doing that right now for some text line art rendering code which was hitting edge cases. If I'd tried to continue to fix edge cases I would be able to fix some of the issues but rewriting looking at the problem from a different angle lets me fix all the cases in a more robust way. We need to do something similar here. I would suggest starting by investigating how other tools are rendering flame charts from the same sort of implicit time range data.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart (hunk 18 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/timeline/timeline_protocol.dart]: done.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart (hunk 16 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/timeline/timeline_protocol.dart]: removed.

File: packages/devtools/lib/src/utils.dart [hunk 26]
```diff
@@ -105,6 +105,16 @@ String funcRefName(FuncRef ref) {
   }
 }
 
+void maybeExecuteWithDelay(bool condition, Duration delay, void callback()) {
```
Comment (jacob314) [inline packages/devtools/lib/src/utils.dart]: maybeExecuteWithDelay -> executeWithDelay

maybe change condition to executeNow and make it an optional named parameter?

File: packages/devtools/test/utils_test.dart [hunk 27]
```diff
@@ -62,5 +64,21 @@ void main() {
       expect(log2(3), equals(1));
       expect(log2(4), equals(2));
     });
+
+    test('maybeExecuteWithDelay', () async {
+      int n = 1;
+
+      // Condition n >= 2 is false, so we should execute with a delay.
+      maybeExecuteWithDelay(n >= 2, const Duration(milliseconds: 500), () => n++);
```
Comment (jacob314) [inline packages/devtools/test/utils_test.dart]: these tests don't verify that the execution really happened after the specified delay. Use the current time to verify that they don't run early or run significantly later using some time epsilon or a mocked out timer to avoid flakes.

File: packages/devtools/lib/src/timeline/timeline_protocol.dart [hunk 28]
```diff
@@ -13,7 +13,10 @@ import 'package:meta/meta.dart';
 import '../utils.dart';
 
 // For documentation, see the Chrome "Trace Event Format" document:
-// https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview
+// https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview.
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline_protocol.dart]: nit: remove the /preview
?

File: packages/devtools/lib/src/utils.dart [hunk 29]
```diff
@@ -7,10 +7,13 @@ import 'dart:convert';
 import 'dart:io';
 import 'dart:math';
 
+import 'package:collection/collection.dart';
 import 'package:intl/intl.dart';
 import 'package:path/path.dart' as path;
 import 'package:vm_service_lib/vm_service_lib.dart';
 
+bool collectionEquals(e1, e2) => const DeepCollectionEquality().equals(e1, e2);
```
Comment (jacob314) [inline packages/devtools/lib/src/utils.dart]: specify types for e1 and e2 potentially using equality.

File: packages/devtools/test/timeline_protocol_test.dart [hunk 30]
```diff
@@ -3,89 +3,794 @@
...
+  final originalGoldenCpuEvent = goldenCpuTimelineEvent.deepCopy();
+  final originalGoldenGpuEvent = goldenGpuTimelineEvent.deepCopy();
+  final originalGoldenCpuTraceEvents = List.of(goldenCpuTraceEvents);
+  final originalGoldenGpuTraceEvents = List.of(goldenGpuTraceEvents);
+
+  setUp(() {
+    // If any of these expect statements fail, a golden was modified while the
+    // tests were running. Do not modify the goldens. Instead, make a copy and
+    // modify the copy.
+    expect(goldenCpuString() == originalGoldenCpuEvent.toString(), isTrue);
```
Comment (jacob314) [inline packages/devtools/test/timeline_protocol_test.dart]: nit: make these asserts instead of expect. These aren't things we have having the test verify but invariants that make the test bogus if they are false.

File: packages/devtools/lib/src/timeline/timeline.dart [hunk 31]
```diff
@@ -233,4 +237,84 @@ class TimelineScreen extends Screen {
...
+          if (timelineController
+              .timelineData.heaps[TimelineEventType.gpu.index].isNotEmpty) {
+            buf.writeln('\nGPU heap');
+            for (TraceEventWrapper wrapper in timelineController
+                .timelineData.heaps[TimelineEventType.gpu.index]
+                .toList()) {
+              buf.writeln(wrapper.event.json.toString());
+            }
+          }
+          downloadFile(buf.toString(), 'tracking_status.txt');
```
Comment (jacob314) [inline packages/devtools/lib/src/timeline/timeline.dart]: nit: make tracking_status.txt a more clear name.

File: packages/devtools/test/utils_test.dart [hunk 32]
```diff
@@ -62,5 +64,54 @@ void main() {
...
+      await Future.delayed(const Duration(milliseconds: 250));
+      expect(n, equals(1));
+      expect(end, isNull);
+      await Future.delayed(const Duration(milliseconds: 250));
+      expect(n, equals(2));
+      expect(end, isNotNull);
+
+      // 10 ms is arbitrary. This can be increased if this test starts to flake.
+      const epsilonMs = 10;
+      final delayedAsExpected = (end - start) > (delayMs - epsilonMs) &&
```
Comment (jacob314) [inline packages/devtools/test/utils_test.dart]: simpler: take the . abs value of the delta and make sure it is within the epsilon.
expect(abs(end-start - delayMs), lessThan(epsilonMs))
there should be already a lessThan matcher or similar.

File: packages/devtools/lib/src/utils.dart [hunk 33]
```diff
@@ -7,10 +7,14 @@ import 'dart:convert';
 import 'dart:io';
 import 'dart:math';
 
+import 'package:collection/collection.dart';
 import 'package:intl/intl.dart';
 import 'package:path/path.dart' as path;
 import 'package:vm_service_lib/vm_service_lib.dart';
 
+bool collectionEquals<T>(T e1, T e2) =>
```
Comment (jacob314) [inline packages/devtools/lib/src/utils.dart]: can this be:
<T extends Collection>
?

File: packages/devtools/test/utils_test.dart [hunk 34]
```diff
@@ -62,5 +64,54 @@ void main() {
...
+      // Condition n >= 2 is true, so we should not execute with a delay.
+      end = null;
+      start = DateTime.now().millisecondsSinceEpoch;
+      executeWithDelay(
+        const Duration(milliseconds: 500),
+        () {
+          n++;
+          end = DateTime.now().millisecondsSinceEpoch;
+        },
+        executeNow: n >= 2,
```
Comment (jacob314) [inline packages/devtools/test/utils_test.dart]: just make this
executeNow: true,

in general, test code should be as straightforward as possible.

Comment (kenzieschmoll) [reply packages/devtools/test/utils_test.dart]: done.

File: packages/devtools/test/utils_test.dart (hunk 32 above)
Comment (kenzieschmoll) [reply packages/devtools/test/utils_test.dart]: done.

File: packages/devtools/lib/src/utils.dart (hunk 33 above)
Comment (kenzieschmoll) [reply packages/devtools/lib/src/utils.dart]: reverted to dynamic since we won't benefit from type checking here

File: packages/devtools/test/timeline_protocol_test.dart (hunk 30 above)
Comment (kenzieschmoll) [reply packages/devtools/test/timeline_protocol_test.dart]: I originally had asserts, but when those failed they did not make the test fail.
